trigger:
- main

jobs:
- job: DevPlan
  displayName: 'Dev Plan'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
  - script: |
      terraform init -backend-config="path=dev.tfstate"
      terraform plan -out=dev.plan
    displayName: 'Terraform Init and Plan for Dev'

- job: DevApply
  displayName: 'Dev Apply'
  dependsOn: DevPlan
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
  - script: |
      terraform init -backend-config="path=dev.tfstate"
      terraform apply "dev.plan"
    displayName: 'Terraform Apply for Dev'

- job: LivePlan
  displayName: 'Live Plan'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
  - script: |
      terraform init -backend-config="path=live.tfstate"
      terraform plan -out=live.plan
    displayName: 'Terraform Init and Plan for Live'

- job: LiveApply
  displayName: 'Live Apply'
  dependsOn: LivePlan
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
  - script: |
      terraform init -backend-config="path=live.tfstate"
      terraform apply "live.plan"
    displayName: 'Terraform Apply for Live'